service: inoservey-ethereumAPI

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    packager: "yarn"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-2

functions:
  api:
    handler: src/api.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      origin: '*'

